spring:
  application:
    name: draft-predict

  datasource:
    url: jdbc:postgresql://localhost:5432/daily_plan_project
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: java2905

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  key: ${API_KEY}
  request:
    delay: ${API_REQUEST_DELAY}
  queue:
    id: ${API_QUEUE_ID}
  patch: ${API_PATCH}
