spring:
  application:
    name: draft-predict
  profiles:
    active: dev
  main:
    banner-mode: off
    allow-circular-references: off
  flyway:
    baseline-on-migrate: true

api:
  key: ${API_KEY}
  request:
    delay: ${API_REQUEST_DELAY}
  queue:
    id: ${API_QUEUE_ID}
  patch: ${API_PATCH}
